- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false
  become: yes

- name: Update Packages
  yum: name=* state=latest
  become: yes

- name: Install Common packages
  yum: name={{ item }} state=present
  with_items:
    - git
    - python3
    - firewalld
    - python3-libsemanage
    - python3-libselinux
  become: yes

- name: Set authorized keys taken from url
  authorized_key:
    user: ec2-user
    state: present
    key: http://paste.openstack.org/raw/osn4Yi7NFIb6PsYpRkT8/
  become: yes
