- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false

- name: Update Packages
  yum: name=* state=latest

- name: Install Common packages
  yum: name={{ item }} state=present
  with_items:
    - git
    - python3
    - firewalld
    - python3-libsemanage
    - python3-libselinux
