---
# These tasks are responsible for copying the latest dev/production code from
# the version control system.
- name: Create directory
  file:
    path: /app/src
    state: directory
    group: app
    owner: app
  become: yes

- name: Copy the code from repository
  become: yes
  become_user: app
  git: repo={{ repository }} dest=/app/src
