---
# These tasks install nginx

- name: Install nginx
  yum: name={{ item }} state=present
  with_items:
    - nginx
  become: yes


- name: Insert firewalld rule for http
  firewalld:
    zone: public
    permanent: yes
    service: http
    state: enabled
  notify: restart firewall
  become: yes

- name: Insert firewalld rule for https
  firewalld:
    zone: public
    permanent: yes
    service: https
    state: enabled
  notify: restart firewall
  become: yes

- name: nginx service state
  service: name=nginx state=started enabled=yes
  become: yes

- name: Configure SELinux to allow httpd to connect to remote database
  seboolean: name=httpd_can_network_connect_db state=true persistent=yes
  when: sestatus.rc != 0
  become: yes

- name: Add the user 'app'
  user:
    name: app
    comment: user of the app
  become: yes

- name: Create a new default file for nginx
  template: src=../templates/nginx_config.j2 dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
  become: yes
