---
# Handler to handle DB tier notifications

- name: restart mysql
  service: name=mysqld state=restarted
  become: yes

- name: restart firewall
  service: name=firewalld state=restarted
  become: yes
