---
# This playbook deploys the whole application stack in this site.
- name: apply common configuration to all nodes
  hosts: all
  remote_user: ec2-user
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - ./global_vars/all.yml

  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: webservers
  remote_user: ec2-user
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - ./global_vars/all.yml

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: dbservers
  remote_user: ec2-user
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - ./global_vars/all.yml
    - ./global_vars/dbserver.yml

  roles:
    - db
